Task: SnowPetrel
scorer: Adam-Al-Rahman
date: Oct9

# Project path (change when moving around)
project_path: SnowPetrel\SnowPetrel-Adam-2024-10-09

engine: pytorch

bodyparts:
- head
- beak_base
- beak_tip
- neck
- body1
- body2
- tail_base

# Plotting configuration
skeleton:
- - head
  - beak_base
- - beak_base
  - beak_tip
- - head
  - neck
- - neck
  - body1
- - body1
  - body2
- - body2
  - tail_base
skeleton_color: black
pcutoff: 0.6
dotsize: 4
alphavalue: 0.7